[tool.poetry]
name = "portfolio-backend-fastapi"
version = "0.1.0"
description = ""
authors = ["Dima <dima.horbal.dev@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
