import os

APP_SECRET = os.getenv("APP_SECRET")
GOOGLE_PROJECT_ID = os.getenv("GOOGLE_PROJECT_ID")
RECAPTCHA_API_KEY = os.getenv("RECAPTCHA_API_KEY")
RECAPTCHA_SECRET_KEY = os.getenv("RECAPTCHA_SECRET_KEY")
